The goal of this homework is to create a regression model for predicting the car fuel efficiency (column 'fuel_efficiency_mpg').

In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
#1. load data

df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [3]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [5]:
for col in df.columns:
    print(col,':', df[col].dtype)

model_year : int64
origin : str
fuel_type : str
drivetrain : str
num_doors : int64
engine_displacement : int64
num_cylinders : int64
horsepower : float64
vehicle_weight : int64
acceleration : float64
fuel_efficiency_mpg : float64

In [6]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [7]:
df.fillna(0, inplace=True)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,0.0,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,0.0,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [8]:
df.fuel_efficiency_mpg.value_counts()

fuel_efficiency_mpg
30.2    150
29.6    148
30.9    142
31.3    141
31.4    141
       ...
20.9      1
41.2      1
19.8      1
20.7      1
21.4      1
Name: count, Length: 188, dtype: int64

In [9]:
df.describe().round()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0
mean,2000.0,4.0,2269.0,6.0,232.0,4287.0,18.0,30.0
std,14.0,1.0,183.0,1.0,75.0,266.0,3.0,3.0
min,1975.0,2.0,1590.0,4.0,0.0,3320.0,0.0,20.0
25%,1987.0,3.0,2150.0,6.0,234.0,4110.0,18.0,28.0
50%,2000.0,4.0,2270.0,6.0,252.0,4280.0,19.0,30.0
75%,2012.0,4.0,2390.0,6.0,268.0,4470.0,20.0,32.0
max,2024.0,5.0,3110.0,8.0,334.0,5460.0,24.0,41.0

In [10]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=1
)

In [11]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [45]:
y_train = (df_train.fuel_efficiency_mpg).values
y_val = (df_val.fuel_efficiency_mpg).values
y_test = (df_test.fuel_efficiency_mpg).values

AttributeError: 'DataFrame' object has no attribute 'fuel_efficiency_mpg'

In [ ]:
del df_train['fuel_efficiency_mpg']
del df_val['fuel_efficiency_mpg']
del df_test['fuel_efficiency_mpg']

In [ ]:
# Question 1. Which original feature is used for splitting the data? If you use DictVectorizer, map a one-hot feature such as origin=USA back to its original column name.

from sklearn.tree import DecisionTreeRegressor
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import roc_auc_score
from sklearn.tree import export_text

In [46]:
df_train.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration
0,2011,USA,Gasoline,Front-wheel drive,4,2370,6,284.0,4280,19.0
1,2012,USA,Diesel,All-wheel drive,3,2460,6,288.0,4580,18.8
2,1985,Europe,Gasoline,All-wheel drive,3,2070,6,230.0,4150,20.6
3,2005,Europe,Diesel,Front-wheel drive,5,2050,5,249.0,4120,0.0
4,2004,Asia,Gasoline,Front-wheel drive,2,2160,6,241.0,4020,17.9

In [47]:
train_dicts = df_train.fillna(0).to_dict(orient='records')

dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)

In [48]:
train_dicts
y_train

array([30.8, 29.7, 27.6, ..., 30.7, 32.1, 29.6], shape=(6000,))

In [49]:
dt = DecisionTreeRegressor(max_depth=1, random_state=1)
dt.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=1, random_state=1)

In [50]:
print(export_text(
    dt,
    feature_names=list(dv.get_feature_names_out())
))

|--- model_year <= 1997.50
|   |--- value: [28.61]
|--- model_year >  1997.50
|   |--- value: [31.17]

In [51]:
feature_idx = dt.tree_.feature[0]
feature_name = dv.get_feature_names_out()[feature_idx]

print(feature_name)

model_year

In [52]:
val_dicts = df_val.fillna(0).to_dict(orient='records')
X_val = dv.transform(val_dicts)

y_pred = dt.predict(X_val)

In [57]:
# Question 2. Train a random forest regressor with these parameters:

from sklearn.ensemble import RandomForestRegressor

In [58]:
rf = RandomForestRegressor(n_estimators=10,
                           n_jobs=-1,
                           random_state=1)
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, n_jobs=-1, random_state=1)

In [59]:
rmese = np.sqrt(((y_val - rf.predict(X_val)) ** 2).mean())

In [60]:
print(rmese)

1.8336350509302553

In [62]:
# Question 3. Train random forest regressors with different numbers of trees: 10, 50, 100, and 200. For each model, calculate the RMSE on the validation dataset.
for n in [10, 50, 100, 200]:
    rf = RandomForestRegressor(n_estimators=n,
                               n_jobs=-1,
                               random_state=1)
    rf.fit(X_train, y_train)
    rmese = np.sqrt(((y_val - rf.predict(X_val)) ** 2).mean())
    print(n, round(rmese,3))

10 1.834
50 1.77
100 1.768
200 1.767

In [63]:
# Question 4. Let's select the best max_depth
for max_depth in [10, 15, 20, 25]:
    for n in [10, 50, 100, 200]:
        rf = RandomForestRegressor(n_estimators=n,
                                   max_depth=max_depth,
                                   n_jobs=-1,
                                   random_state=1)
        rf.fit(X_train, y_train)
        rmese = np.sqrt(((y_val - rf.predict(X_val)) ** 2).mean())
        print(max_depth, n, round(rmese,3))

10 10 1.785
10 50 1.75
10 100 1.746
10 200 1.745
15 10 1.834
15 50 1.773
15 100 1.767
15 200 1.765
20 10 1.83
20 50 1.77
20 100 1.765
20 200 1.765
25 10 1.84
25 50 1.772
25 100 1.769
25 200 1.768

In [66]:
# Question 5. What's the most important feature (among these 4)?
rf = RandomForestRegressor(n_estimators=10,
                           max_depth=20, 
                           n_jobs=-1,
                           random_state=1)
rf.fit(X_train, y_train)
print(rf.feature_importances_)

[0.05546622 0.00787275 0.0200048  0.00563607 0.06100789 0.02112758
 0.16071286 0.01168541 0.07825357 0.29582159 0.00693892 0.01972375
 0.00647862 0.00338878 0.04223247 0.20364873]

In [73]:
feature_importance = pd.Series(
    rf.feature_importances_,
    index=dv.get_feature_names_out()
)

feature_importance.sort_values(ascending=False)

model_year                      0.295822
vehicle_weight                  0.203649
fuel_type=Gasoline              0.160713
horsepower                      0.078254
engine_displacement             0.061008
acceleration                    0.055466
origin=USA                      0.042232
fuel_type=Diesel                0.021128
drivetrain=Front-wheel drive    0.020005
num_doors                       0.019724
fuel_type=Hybrid                0.011685
drivetrain=All-wheel drive      0.007873
num_cylinders                   0.006939
origin=Asia                     0.006479
drivetrain=Rear-wheel drive     0.005636
origin=Europe                   0.003389
dtype: float64

In [74]:
# Question 6. Which eta leads to the best RMSE score on the validation dataset?
import xgboost as xgb

In [75]:
features = list(dv.get_feature_names_out())
dtrain = xgb.DMatrix(X_train, label=y_train, feature_names=features)
dval = xgb.DMatrix(X_val, label=y_val, feature_names=features)

In [76]:
xgb_params = {
    'eta': 0.3, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    
    'seed': 1,
    'verbosity': 1,
}

In [77]:
model = xgb.train(xgb_params, dtrain, num_boost_round=100)

In [80]:
y_pred = model.predict(dval)
rmse = np.sqrt(((y_val - y_pred) ** 2).mean())
print(f"RMSE: {rmse}")

RMSE: 1.8264579799904583

In [81]:
xgb_params = {
    'eta': 0.1, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    
    'seed': 1,
    'verbosity': 1,
}
model = xgb.train(xgb_params, dtrain, num_boost_round=100)

y_pred = model.predict(dval)
rmse = np.sqrt(((y_val - y_pred) ** 2).mean())
print(f"RMSE: {rmse}")

RMSE: 1.724810059827976